PFGE/PFGE/Models/Place.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace PFGE.Models
{
    [Bind(Exclude = "PlaceId")]
    public class Place
    {
        [Key]
        public int PlaceId { get; set; }
        [Required]
        public string Heading { get; set; }
        [Required]
        public string City { get; set; }
        public string Address { get; set; }
        [Required]
        public double Latitude { get; set; }
        [Required]
        public double Longitude { get; set; }

        public string UserID { get; set; }
    }

    public class PlacePhoto
    {
        [Key]
        public int PlacePhotoId { get; set; }
        [Required]
        public int PlaceId { get; set; }
        [Required]
        public string PhotoName { get; set; }
        //[Required]
        public string PhotoDescription { get; set; }
    }

    //[Bind(Exclude = "EventId")]
    //public class Event
    //{
    //    [Key]
    //    public int EventId { get; set; }
    //    [Required]
    //    public string EventName { get; set; }
    //    [Required]
    //    public DateTime EventDate { get; set; }
    //    [Required]
    //    public string EventDescription { get; set; }
    //}

    //[Bind(Exclude = "EventPhotoId")]
    //public class EventPhoto
    //{
    //    [Key]
    //    public int EventPhotoId { get; set; }
    //    [Required]
    //    public int EventId { get; set; }
    //    [Required]
    //    public string PhotoName { get; set; }
    //    [Required]
    //    public string PhotoDescription { get; set; }
    //}


}

PFGE/PFGE/Controllers/PlacesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PFGE.Models;
using System.IO;

namespace PFGE.Controllers
{
    public class PlacesController : Controller
    {
        //
        // GET: /Places/
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult AddPlace()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddPlace(Place place)
        {
            PFGEEntities db = new PFGEEntities();

            //Place place = new Place();
            //place.Address = "test";
            //place.City = "test";
            //place.Heading = "test";
            //place.Latitude = 0;
            //place.Longitude = 0.0;

            db.Places.Add(place);
            db.SaveChanges();
            Response.Cookies.Add(new HttpCookie("place", place.PlaceId.ToString()));

            return RedirectToAction("AddImages");
        }

        public ActionResult ViewPlaces()
        {
            PFGEEntities db = new PFGEEntities();
            var list = from lst in db.Places select lst;
            return View(list);
        }

        public ActionResult AddImages()
        {
            return View();
        }

        [HttpPost]
        public ActionResult UploadFile()
        {
            int placeId = 0;

            placeId = Convert.ToInt32(Request.Cookies["place"].Value.ToString());

            string directory = base.Server.MapPath("~/Uploadings/" + placeId.ToString());
                       
            if (!Directory.Exists(directory))
            {
                Directory.CreateDirectory(directory);
            }

            //we process it distinct ways based on a browser
            //find more info here http://stackoverflow.com/questions/4884920/mvc3-valums-ajax-file-upload
            Stream stream = null;
            var fileName = "";
            var contentType = "";
            if (String.IsNullOrEmpty(Request["qqfile"]))
            {
                // IE
                HttpPostedFileBase httpPostedFile = Request.Files[0];
                if (httpPostedFile == null)
                    throw new ArgumentException("No file uploaded");
                stream = httpPostedFile.InputStream;
                fileName = Path.GetFileName(httpPostedFile.FileName);
                contentType = httpPostedFile.ContentType;
            }
            else
            {
                //Webkit, Mozilla
                stream = Request.InputStream;
                fileName = Request["qqfile"];
            }

            ////int shoppingCartItemID = 0;

            ////shoppingCartItemID = int.Parse(Request.QueryString["shoppingCartItemID"].ToString());

            var fileBinary = new byte[stream.Length];
            stream.Read(fileBinary, 0, fileBinary.Length);

            var fileExtension = Path.GetExtension(fileName);
            if (!String.IsNullOrEmpty(fileExtension))
                fileExtension = fileExtension.ToLowerInvariant();

            string filePath = directory + fileName;

            System.IO.File.WriteAllBytes(filePath, fileBinary);

            ////(new ShoppingCartFilesServices()).Insert(shoppingCartItemID, fileName, filePath, DateTime.Now.ToString("dd-MMM-yyyy"), "");

            //int fileMaxSize = _catalogSettings.FileUploadMaximumSizeBytes;
            //if (fileBinary.Length > fileMaxSize)
            //{
            //    //when returning JSON the mime-type must be set to text/plain
            //    //otherwise some browsers will pop-up a "Save As" dialog.
            //    return Json(new
            //    {
            //        success = false,
            //        message = string.Format(_localizationService.GetResource("ShoppingCart.MaximumUploadedFileSize"), (int)(fileMaxSize / 1024)),
            //        downloadGuid = Guid.Empty,
            //    }, "text/plain");
            //}

            //var download = new Download()
            //{
            //    DownloadGuid = Guid.NewGuid(),
            //    UseDownloadUrl = false,
            //    DownloadUrl = "",
            //    DownloadBinary = fileBinary,
            //    ContentType = contentType,
            //    //we store filename without extension for downloads
            //    Filename = Path.GetFileNameWithoutExtension(fileName),
            //    Extension = fileExtension,
            //    IsNew = true
            //};
            //_downloadService.InsertDownload(download);

            PFGEEntities db = new PFGEEntities();
            PlacePhoto placePhoto = new PlacePhoto();
            placePhoto.PlaceId = placeId;
            placePhoto.PhotoName = fileName;
            //placePhoto.PhotoDescription = "";
            db.PlacePhotos.Add(placePhoto);
            db.SaveChanges();

            //when returning JSON the mime-type must be set to text/plain
            //otherwise some browsers will pop-up a "Save As" dialog.
            return Json(new
            {
                success = true,
                message = "uploaded sussessfully",
                downloadGuid = Guid.NewGuid(),
            }, "text/plain");
        }

        //public ActionResult ShoppingCartFiles(int id)
        //{
        //    var shoppingCartFiles = (new ShoppingCartFilesServices()).SelectByShoppingCartItemID(id);
        //    return View(shoppingCartFiles);
        //}

        //public JsonResult DeletePrintFile(int id)
        //{
        //    var shoppingCartFiles = (new ShoppingCartFilesServices()).SelectByFileID(id);
        //    string path = shoppingCartFiles.FirstOrDefault().FilePath;
        //    if (System.IO.File.Exists(path))
        //    {
        //        System.IO.File.Delete(path);
        //    }
        //    (new ShoppingCartFilesServices()).Delete(id);
        //    return Json(new { success = true }, "text/html");
        //    //return View(shoppingCartFiles);
        //}
	}
}

PFGE/PFGE/Views/Places/AddImages.cshtml
@{
    ViewBag.Title = "Add Images";
    //Layout = "~/Views/_MainPage.cshtml";
}

@section Scripts {
     <link href="~/Content/fileuploader/fileuploader.css" rel="stylesheet">
     <script src="~/Scripts/fileuploader.js"></script>
    
<script type="text/javascript">
    $(function () {
        var PrintItemUploader = new qq.FileUploader({
            element: document.getElementById('PrintItemUploader'),
            action: '/Places/UploadFile',
            onComplete: function (id, fileName, responseJSON) {
                $("#PrintItemUpload").val(responseJSON.downloadGuid);
                if (responseJSON.message) {
                    alert(responseJSON.message);
                    //window.location.href = "@Request.RawUrl";
            }
        },
            //allowedExtensions:'.txt',
            strings: {
                upload: "upload",
                drop: "drop",
                cancel: "cancel",
                failed: "failed"
            }
        });
    });
</script>
}


<div >
    <div class="row">
        <div class="col-md-12">
        <h2>Add Images</h2>
        <div class="well">              
            <div id="PrintItemUploader">
                            
            </div>       
        </div>
    </div>     

    </div>
</div>

PFGE/PFGE/Views/Places/AddPlace.cshtml
@model PFGE.Models.Place

@{
    ViewBag.Title = "Add Place";
    //Layout = "~/Views/_MainPage.cshtml";
}


@section Scripts {
    <script src="http://maps.googleapis.com/maps/api/js?key=AIzaSyDY0kkJiTPVd2U7aTOAwhc9ySH6oHxOIYM&sensor=false"
        type="text/javascript"></script>

   @* //register CSS and JS
    
    

    //ex. ['jpg', 'jpeg', 'png', 'gif'] or []
    //var allowedFileExtensions = string.Join(", ", attribute.AllowedFileExtensions.Select(x => "'" + x.Trim() + "'").ToList());*@

}

<script>
    var myCenter = new google.maps.LatLng(51.508742, -0.120850);
    var marker;
    var map = null;
    var geocoder = null;

    function initialize() {
        //geocoder = new google.maps.Geocoder();

        //var mapProp = {
        //    center: myCenter,
        //    zoom: 15,
        //    mapTypeId: google.maps.MapTypeId.ROADMAP
        //};
        //var map = new google.maps.Map(document.getElementById("googleMap"), mapProp);
        //marker = new google.maps.Marker({
        //    position: myCenter,
        //    draggable: true
        //    // icon:'themes/assets/images/nepali-momo.png',
        //    //animation: google.maps.Animation.BOUNCE
        //});

        //marker.setMap(map);

        //// Info open
        //var infowindow = new google.maps.InfoWindow({
        //    content: "Hello World!"
        //});

        //google.maps.event.addListener(marker, 'click', function () {
        //    //infowindow.open(map, marker);
        //});
    }
    //google.maps.event.addDomListener(window, 'load', initialize);

    function showAddr() {
        //alert("show addr called");
        showAddress(document.getElementById("Address").value)
    }

    function showAddress(address) {
        //alert("addr calling");

        geocoder = new google.maps.Geocoder();

        var mapProp = {
            center: myCenter,
            zoom: 15,
            mapTypeId: google.maps.MapTypeId.ROADMAP
        };
        var map = new google.maps.Map(document.getElementById("googleMap"), mapProp);

        geocoder.geocode({ 'address': address }, function (results, status) {
            if (status == google.maps.GeocoderStatus.OK) {
                //alert("ok");
                map.setCenter(results[0].geometry.location);
                //var marker = new google.maps.Marker({
                //    map: map,
                //    position: results[0].geometry.location
                //});
                // Place a draggable marker on the map
                var marker = new google.maps.Marker({
                    position: results[0].geometry.location,
                    map: map,
                    draggable: true,
                    title: "Drag me!"
                });

                google.maps.event.addListener(marker, 'dragend', function (event) {
                    //placeMarker(event.latLng);
                    document.getElementById("Latitude").value = event.latLng.lat();
                    document.getElementById("Longitude").value = event.latLng.lng();
                });

                document.getElementById("Latitude").value = results[0].geometry.location.lat();
                document.getElementById("Longitude").value = results[0].geometry.location.lng();

            } else {
                alert('Geocode was not successful for the following reason: ' + status);
            }
        });

                
        //if (geocoder) {
        //    geocoder.getLatLng(
        //      address,
        //      function (point) {
        //          if (!point) {
        //              alert(address + " not found");
        //          } else {
        //              //map.clearOverlays();
        //              //map.setCenter(point, 13);
        //              //var marker = new GMarker(point, { draggable: true });

        //              marker = new google.maps.Marker({
        //                  position: myCenter,
        //                  draggable: true
        //                  // icon:'themes/assets/images/nepali-momo.png',
        //                  //animation: google.maps.Animation.BOUNCE
        //              });


        //              marker.setMap(map);
        //              ////map.addOverlay(marker);
        //              //GEvent.addListener(marker, "dragstart", function () {

        //              //    map.closeInfoWindow();
        //              //});

        //              google.maps.event.addListener(marker, 'click', function () {
        //                  map.setZoom(8);
        //                  map.setCenter(marker.getPosition());
        //              });


        //              google.maps.event.addListener(marker, "dragend", function (point, placemark) {
        //                  //var point1=GMarker.getLatLng()

        //                  document.getElementById("LatitudeTextBox").value = point.y;
        //                  document.getElementById("LongitudeTextBox").value = point.x;


        //                  marker.openInfoWindowHtml("<br>Long: " + point.x + "<br>Lati:  " + point.y);
        //                  // marker.openInfoWindowHtml(address );
        //              });
        //              //map.addOverlay(marker);

        //              document.getElementById("LatitudeTextBox").value = point.y;
        //              document.getElementById("LongitudeTextBox").value = point.x;
        //              marker.openInfoWindowHtml(address + "<br>Long: " + point.x + "<br>Lati:  " + point.y);
        //          }
        //      }
        //    );


        //}
        alert("Address found");
        //marker.setMap(map);
        //map.setCenter(marker.getPosition());
    }


</script>


<div >
    <div class="row">
        <div class="col-md-12">
        <h2>Do your part</h2>
        <div class="well">
                @using (Html.BeginForm())
                {
                    <p>Heading:  @Html.TextBoxFor(model => model.Heading)</p>
                    <p>
                        City: @Html.TextBoxFor(model => model.City)
                    </p>
                    <p>
                        Address: @Html.TextBoxFor(model => model.Address) <input type="button" id="Button1" onclick="showAddr(); return false"
                            value="Search" />
                    </p>
                    <p>
                        <div id="googleMap" style="height: 300px;"></div>
                    </p>
                    <p>
                        Latitude: @Html.TextBoxFor(model => model.Latitude)
                    </p>
                    <p>
                        Longitude: @Html.TextBoxFor(model => model.Longitude)
                    </p>
                    <input id="cmdSubmit" type="submit" value="Submit" />   <input id="cmdCancel" value="Cancel" type="button" />
                    <br />
                     <input id="PrintItemUpload" name="PrintItemUpload" type="hidden" />
                } 
       
        </div>
    </div>     

    </div>
</div>

  @*@Html.Action(storeLocation + "checkout/ShoppingCartFiles/"+ item.Id);
                            @Html.Action("ShoppingCartFiles", "Places", new { id = 1 })   *@                         
                           
 
                            @*<span class="product-unit-price">@item.UnitPrice</span>*@

PFGE/PFGE/Views/Places/ViewPlaces.cshtml
@model IEnumerable<PFGE.Models.Place>
@{
    ViewBag.Title = "ViewPlaces";
    Layout = "~/Views/_MainPage.cshtml";
}


@section headcontent {
    <script src="http://maps.googleapis.com/maps/api/js?key=AIzaSyDY0kkJiTPVd2U7aTOAwhc9ySH6oHxOIYM&sensor=false"
        type="text/javascript"></script>
}

    <script>
        // If you're adding a number of markers, you may want to
        // drop them on the map consecutively rather than all at once.
        // This example shows how to use setTimeout() to space
        // your markers' animation.
        
        var marker;
        var map = null;
        var geocoder = null;


        var berlin = new google.maps.LatLng(30.7333148,76.7794179);

        var neighborhoods = [@{foreach (var lst in Model.ToList())
                {
                   <text>new google.maps.LatLng( @lst.Latitude.ToString(),@lst.Longitude.ToString() ) @{if (!(lst.PlaceId == Model.Last().PlaceId)){<text>,</text>}}</text>
                }}];

        var markers = [];
        var iterator = 0;

        function initialize() {
            var mapOptions = {
                zoom: 12,
                center: berlin,
                mapTypeId: google.maps.MapTypeId.ROADMAP
            };

            map = new google.maps.Map(document.getElementById('googleMap'),
                    mapOptions);
        }

        function drop() {
            //alert("calling map");
            for (var i = 0; i < neighborhoods.length; i++) {
                setTimeout(function () {
                    addMarker(i);
                },200);
            }
            //alert("map called");
        }

        function addMarker(i) {

            var mymarker = new google.maps.Marker({
                position: neighborhoods[iterator],
                map: map,
                draggable: false,
                animation: google.maps.Animation.DROP
            })

            //marker.addListener('click', function () {
            //   alert("hello");
            //});

            google.maps.event.addListener(mymarker, 'click', function () {
                alert("hello : " + i);
            });

            //mymarker.openInfoWindowHtml("hello : " + iterator);

            //google.maps.event.addListener(mymarker, 'click', function () {
            //    map.setZoom(8);
            //    map.setCenter(marker.getPosition());
            //});

            markers.push(mymarker);
            iterator++;
        }

        google.maps.event.addDomListener(window, 'load', initialize);

    </script>

@using (Html.BeginForm()) {

      <input type="button" value="Show Places" id="drop1" onclick="drop(); return false" />
         
      
     
<p>Places</p>
    <p>
<div style="clear:both"></div>
    <div id="googleMap" style="height: 400px;"></div></p>
    <input type="submit" id="myval" />
}
<div style="clear:both"></div>